version: '3'
services:
  azure-storage:
    image: azure-storage
    build:
      context: ./video-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - STORAGE_CONNECTION_STRING=?conn-str?
    restart: "no"
  video-streaming:
    image: video-streaming
    build:
      context: ./video-stream
      dockerfile: Dockerfile
    container_name: video-stream
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"
