version: '3'
services:
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "4000:27017"
    restart: always
  azure-storage:
    image: azure-storage
    build:
      context: ./video-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_CONNECTION_STRING=?conn-str?
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-stream
      dockerfile: Dockerfile
    container_name: video-stream
    restart: on-failure
    ports:
      - "4002:80"
    depends_on:
      - rabbit
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - DB_HOST=mongodb://db:27017/video-streaming
      - DBHOST=mongodb://db:27017

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile
    container_name: history
    restart: on-failure
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - RABBIT=amqp://guest:guest@rabbit:5672
    depends_on:
      - db
      - rabbit

  rabbit:
    image: rabbitmq:3.8.1-management
    container_name: rabbit
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: always
