version: "3"
services:
  mongodb:
    image: mongo:latest
    restart: "no"
    container_name: mongodb
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb

  rabbit:
    image: rabbitmq:3.8.1-management
    container_name: rabbit
    restart: "no"
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672

  azure-storage:
    image: azure-storage
    build:
      context: ./video-storage
      dockerfile: Dockerfile
    container_name: video-storage
    restart: "no"
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}

  video-streaming:
    image: video-streaming
    build:
      context: ./video-stream
      dockerfile: Dockerfile
    container_name: video-stream
    restart: "no"
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - HISTORY_HOST=history
      - HISTORY_PORT=80
      - RABBIT=${RABBIT}
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - DBHOST=${MONGO_URI}
      - DBCOLLECTION=${DB_COLLECTION}
      - VIEWED_EXCHANGE=${VIEWED_EXCHANGE}
    depends_on:
      - rabbit
      - mongodb

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile
    container_name: history
    restart: "no"
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - RABBIT=${RABBIT}
      - VIEWED_EXCHANGE=${VIEWED_EXCHANGE}
    depends_on:
      - rabbit
