version: '3'
services:
  video:
    image: grierson/video
    build:
      context: ./video
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    environment:
      - PORT=80
    restart: "no"
